### PR TITLE
Update the tests

### PR DESCRIPTION
**Pull request by thilinarmtb**
Currently, I test min, max and add;

May be we can use a unit test framework?

### CODE REVIEW

**Comment by stgeke** [comment]
Can you please fix also this failing tests.

**Comment by thilinarmtb** [comment]
Will do.

**Comment by thilinarmtb** [comment]
I fixed the failing tests `gs_test_old.c`. If travis comes out okay, I think this
can be merges as it is.

**Comment by thilinarmtb** [comment]
I rebased the commit history.

**Comment by misunmin** [comment]
Thanks for the update, Thilina -- Stefan, how would you want to proceed this? Maybe a PR to Nek5000 master and get tested with the master before merging or other suggestion?

**Comment by stgeke** [comment]
I think we can just merge this PR. Upcoming feature release get their own tags or branch that are branched out of master. A Nek5000 release will cherry pick a specific gslib release.

**Comment by misunmin** [comment]
Ok thanks.
________________________________

**Comment by thilinarmtb** [comment]
Thanks guys !! Now we have the green light on `build passing` !! Yay !!

**Pull request merged**
